### ISSUE TITLE
User name overlapping tabs

### ISSUE THREAD

**Issue by antho1404** [liteflow-labs/starter-kit#101]
On the profile page, the name is not limited to the side bar, meaning that in some cases it can overlap the tabs

Here is an example of a profile with overlap

https://demo-bsc-testnet-liteflow.vercel.app/users/0x09ea03548b97aa045043ff55f5bd9505f2f135eb

<img width="918" alt="Screenshot 2022-12-22 at 18 43 00" src="https://user-images.githubusercontent.com/1783126/209127217-785dc9b2-af8e-4c40-8789-c1aed74c5bf6.png">

**Comment by EmmanuelDrouin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [User name overlapping tabs](https://trello.com/c/G7EQMeTB/513-user-name-overlapping-tabs)
