### ISSUE TITLE
Stay on the user results when searching

### ISSUE THREAD

**Issue by antho1404** [liteflow-labs/starter-kit#108]
Another question maybe more for @EmmanuelDrouin What do you think of adding a check when search if we are already on the user's page ? for example if I search a user, I might want to search a user again next. Right now when searching it will always go back to the NFT page, we could add a check to verify if we are on the users page or not and stay on the users page when we search again if we are.

_Originally posted by @achampagnedev in https://github.com/liteflow-labs/starter-kit/issues/97#issuecomment-1363703327_

**Comment by EmmanuelDrouin** [comment]
I agree with this proposal, the logic will apply in the same way for the "collection" part once implemented

**Comment by achampagnedev** [comment]
> @achampagnedev @antho1404 is this issue still valid? From the production point of view this should have been added to the starter kit already (currently waiting a release)

This is included in the PR that should be merged soon, waiting for reviews

**Comment by EmmanuelDrouin** [comment]
Closing this issue as #98 has been merged
