### ISSUE TITLE
Don't throw parse-query errors in service side functions

### ISSUE THREAD

**Issue by NicolasMahe** [liteflow-labs/starter-kit#111]
I think we should not throw error on data parse from URL / query.
Those errors are users' error, not app error.
On prod the user will receive a 500 errors with no explanation.

Example:
https://github.com/liteflow-labs/starter-kit/blob/7ce51793f07ea0f7a7e2edfaae810966566986d0/pages/users/%5Bid%5D/created.tsx#L51-L59

This errors should be 404 errors. Can use the simple `notFound` props:
```
return { notFound: true }
```
Example:
https://github.com/liteflow-labs/starter-kit/blob/aafa50676ea0a989a4db47042203c37e7108ef73/pages/tokens/%5Bid%5D/index.tsx#L124

**Comment by EmmanuelDrouin** [comment]
@antho1404 what do you think of this issue? Is it relevant, and if so should we focus on that? I'm trying to do so clean up on the relevant/irrelevant issues

**Comment by antho1404** [comment]
Still relevant this ensures there is less critical errors (as 500 is a critical error)

**Comment by EmmanuelDrouin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Don't throw parse-query errors in service side functions](https://trello.com/c/X35Gpl5q/522-dont-throw-parse-query-errors-in-service-side-functions)

**Comment by antho1404** [comment]
closing this as this will be handled differently with the update on the ssr https://github.com/liteflow-labs/starter-kit/pull/236
