### ISSUE TITLE
Error when changing wallet and placing bid

### ISSUE THREAD

**Issue by achampagnedev** [liteflow-labs/starter-kit#115]
When changing wallet, if you don't clear your cookies you get this error while trying to place a bit (I suspect this is happening while trying to execute any transaction.

Steps to reproduce:

1. Sign in with an account
2. Swap to an other account via Metamask
3. Try to place a bid
4. Notice error
5. Clear your cookies
6. Login with account
7. Try to place a bid, should work now.

<img width="828" alt="image" src="https://user-images.githubusercontent.com/10590599/210316657-7a62821b-fef5-45e3-baae-c85a9f6dd9a8.png">

**Comment by antho1404** [comment]
Could you make sure that you did sign the login message when switching the account?
I believe this is related, and this message was never signed, and so the token was never generated.

**Comment by EmmanuelDrouin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Error when changing wallet and placing bid](https://trello.com/c/AdV88qLs/512-error-when-changing-wallet-and-placing-bid)

**Comment by NicolasMahe** [comment]
> Could you make sure that you did sign the login message when switching the account? I believe this is related, and this message was never signed, and so the token was never generated.
> 
> If this is the issue, then there is definitely an UX issue here and we should probably block the UI with a modal or so

If this is the issue, then the user should not be logged in.
I think this is the same regression I experienced the last few weeks: The UI says I'm still connected but also ask me to sign the authentication message. If I don't sign it, I'm still "connected" but maybe not 100% connected or something like this.

**Comment by EmmanuelDrouin** [comment]
Closing this issue as I wasn't able to reproduce it on the latest version of the starter kit
