### ISSUE TITLE
Report SSR error to Bugsnag

### ISSUE THREAD

**Issue by NicolasMahe** [liteflow-labs/starter-kit#122]
Need to make sure error from SSR functions are reported to Bugsnag.

**Comment by EmmanuelDrouin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Report error to Bugsnag](https://trello.com/c/Wxhhi888/119-report-error-to-bugsnag)

**Comment by EmmanuelDrouin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Error when changing wallet and placing bid](https://trello.com/c/AdV88qLs/512-error-when-changing-wallet-and-placing-bid)
