### ISSUE TITLE
Add min size to cards on some layouts

### ISSUE THREAD

**Issue by antho1404** [liteflow-labs/starter-kit#134]
With the new card design, some pages displaying cards are broken

<img width="891" alt="Screenshot 2023-01-19 at 13 15 08" src="https://user-images.githubusercontent.com/1783126/213369271-96065db0-e788-4125-8c9d-e496fa44c5a6.png">
<img width="821" alt="Screenshot 2023-01-19 at 13 15 20" src="https://user-images.githubusercontent.com/1783126/213369301-f9802213-b719-44bc-bb84-b034118331df.png">

- Checkout page
- Bid page
- Creation page
- Maybe other

**Comment by EmmanuelDrouin** [comment]
Closing this issue as #136 is merged
