### ISSUE TITLE
New issue with the cards' size when switching languages

### ISSUE THREAD

**Issue by antho1404** [liteflow-labs/starter-kit#135]
New issue with the cards of this size when switching to japanses
<img width="454" alt="Screenshot 2023-01-18 at 16 35 13" src="https://user-images.githubusercontent.com/1783126/213135697-2a754040-b940-426a-ad69-ee5383bdef8f.png">

_Originally posted by @antho1404 in https://github.com/liteflow-labs/starter-kit/pull/132#pullrequestreview-1253104162_

**Comment by EmmanuelDrouin** [comment]
We also have a small issue like that with the coutdown on auction with japenese and chinese ;)

**Comment by EmmanuelDrouin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Low priority - New issue with the cards' size when switching languages](https://trello.com/c/WW4W0zqu/561-low-priority-new-issue-with-the-cards-size-when-switching-languages)

**Comment by antho1404** [comment]
This has been fixed and released in [v1.2.0](https://github.com/liteflow-labs/starter-kit/releases/tag/v1.2.0)
