### ISSUE TITLE
Reserve price should be optional

### ISSUE THREAD

**Issue by NicolasMahe** [liteflow-labs/starter-kit#147]
When creating an auction, there is a label "optional" next to the "reserve price", but it's actually not:

<img width="412" alt="Screenshot 2023-01-26 at 15 23 01" src="https://user-images.githubusercontent.com/5823445/214788756-d9894b7a-bd4e-477d-a688-b3e9f1459832.png">

**Comment by EmmanuelDrouin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Low priority - Reserve price should be optional](https://trello.com/c/HwlzcwX4/560-low-priority-reserve-price-should-be-optional)

**Comment by NicolasMahe** [comment]
closed by https://github.com/liteflow-labs/starter-kit/pull/209
