### ISSUE TITLE
Issue with gif and unlockable content

### ISSUE THREAD

**Issue by antho1404** [liteflow-labs/starter-kit#162]
If a create an unlockable content with a GIF:
- I upload a GIF as the content to Unlock
- I can create my NFT without issue
- After the creation, the media crashes 
  - <img width="970" alt="Screen Shot 2566-02-06 at 12 09 35" src="https://user-images.githubusercontent.com/15095289/216889153-dd0a7028-769b-408f-87f8-271ebf936bcb.png">
  - https://nft-test-bsc-testnet-q6pizabgf-liteflow.vercel.app/tokens/97-0xcfbb45ff528c8ff6542887f631a1f704b92cf7db-60249402084937876423066029128237587855293854847399148942248025622398633406578
  - https://nft-test-bsc-testnet-q6pizabgf-liteflow.vercel.app/tokens/97-0xcfbb45ff528c8ff6542887f631a1f704b92cf7db-60249402084937876423066029128237587855293854847399148942288732701670928521081
- On a token detail page I can't interact with the section bellow the media to toggle the preview or hover the tooltip
  - <img width="624" alt="Screen Shot 2566-02-06 at 12 20 02" src="https://user-images.githubusercontent.com/15095289/216889750-26c41943-e465-4c64-b01f-4738c65fcd7b.png">

If I sign out of the platform, then the NFTs that have issue don't have any anymore and are properly displayed (the issue happen as an owner once connected)

**Connected**
<img width="1288" alt="Screen Shot 2566-02-06 at 12 21 12" src="https://user-images.githubusercontent.com/15095289/216889941-ba5f2057-888b-40d1-a858-4dbbcf2822e8.png">

**Not connected**
<img width="1288" alt="Screen Shot 2566-02-06 at 12 21 22" src="https://user-images.githubusercontent.com/15095289/216890129-4625eae0-9bb2-4b6a-81e7-4c60dd0c34dd.png">

_Originally posted by @EmmanuelDrouin in https://github.com/liteflow-labs/starter-kit/pull/161#pullrequestreview-1284564699_

**Comment by antho1404** [comment]
@EmmanuelDrouin Could you upload the assets you used for that to reproduce

**Comment by EmmanuelDrouin** [comment]
**Assets for** > https://nft-test-bsc-testnet-q6pizabgf-liteflow.vercel.app/tokens/97-0xcfbb45ff528c8ff6542887f631a1f704b92cf7db-60249402084937876423066029128237587855293854847399148942248025622398633406578

Preview
- <img width="547" alt="Screen Shot 2566-02-06 at 12 01 07" src="https://user-images.githubusercontent.com/15095289/217222432-47dcb8fe-cad6-4c8b-a207-260f1a545e7c.png">

Unlockable content
- ![giphy-5](https://user-images.githubusercontent.com/15095289/217223756-62702904-264b-451d-beec-f58066989e45.gif)


**Assets for** > https://nft-test-bsc-testnet-q6pizabgf-liteflow.vercel.app/tokens/97-0xcfbb45ff528c8ff6542887f631a1f704b92cf7db-60249402084937876423066029128237587855293854847399148942288732701670928521081

Preview
- ![giphy-4](https://user-images.githubusercontent.com/15095289/217222957-728b46c8-3920-44c4-a74a-4b3531b0c727.gif)


Unlockable content
- ![giphy-6](https://user-images.githubusercontent.com/15095289/217223802-e7a54e22-c997-470b-92d3-0eb6f9c9210a.gif)

**Comment by NicolasMahe** [comment]
This is an error related to next image, here is an example:
https://liteflow-nft-test-dev-polygon-mumbai.vercel.app/_next/image?url=https%3A%2F%2Fliteflow.mypinata.cloud%2Fipfs%2FQmZPpr9Qy7cU8wHLB4GQtHSK3ZaEc3aHAFTTmobUYMvHq5%3FaccessToken%3DeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpbmRleGVzIjpbIjU0ZTU5OWY2Zjg3ZmU0NjJjMTg0NmM4NDc2NzFkMWRhIl0sImFjY291bnRJZCI6IjJkYWU3ZmMzLWI4OTItNDNjZi05ZGI3LWI1MzZmZTZhOGY3NSIsImlhdCI6MTY3NTc2NjcyNiwiZXhwIjoxNjc1NzcwMzI2fQ.1u4Qcg6yU_kCDjBfx-AKczUu-qfLd2VS2QMFN_JQsZ8&w=3840&q=75

I don't know why it doesn't work with this URL
