### ISSUE TITLE
Fix pagination on filter change

### ISSUE THREAD

**Issue by antho1404** [liteflow-labs/starter-kit#168]
Can you reset pagination to first page after using filters. Pagination is broken if you are not on first page and if there is only 1 page of items after filtering.

![image](https://user-images.githubusercontent.com/33982052/217270610-155a7798-442d-460f-9867-fc17459e214d.png)

_Originally posted by @ismailToyran in https://github.com/liteflow-labs/starter-kit/pull/158#pullrequestreview-1287201091_

**Comment by NicolasMahe** [comment]
Fixed by https://github.com/liteflow-labs/starter-kit/pull/169
