### ISSUE TITLE
Long text on card break the layout

### ISSUE THREAD

**Issue by antho1404** [liteflow-labs/starter-kit#177]
When a title is too long on a card the layout breaks in multiple places

**When creating an offer**
<img width="869" alt="Screenshot 2023-02-10 at 14 12 46" src="https://user-images.githubusercontent.com/1783126/218026272-0fb0a1b3-c712-42c8-ae88-f74d60c4ef66.png">

**On the explore page**
<img width="247" alt="Screenshot 2023-02-10 at 14 13 25" src="https://user-images.githubusercontent.com/1783126/218026360-3549a4a4-a0a3-4e66-814c-ff17fa40b223.png">

**On the home page when there is an auction**
Not the space on the next card
<img width="714" alt="Screenshot 2023-02-10 at 14 14 10" src="https://user-images.githubusercontent.com/1783126/218026484-9fa01e49-423c-4e71-a6ea-7ad9ec23b2d1.png">

**Comment by NicolasMahe** [comment]
I also noticed this issue a few days ago but forget to create the issue:

https://user-images.githubusercontent.com/5823445/218032069-e7dcc4da-35a2-4796-85bc-a498a489f087.mov
