### ISSUE TITLE
Improve pagination component

### ISSUE THREAD

**Issue by antho1404** [liteflow-labs/starter-kit#178]
The explore page is slow the moment the platform has a large number of assets. The API returns the result quite fast, but the rendering takes time.

About 13sec on a platform with about 15k NFTs

<img width="528" alt="Screenshot 2023-02-10 at 15 20 15" src="https://user-images.githubusercontent.com/1783126/218039518-bc508938-529c-4e4f-a755-8f2ca0050cd2.png">

I believe this comes from the pagination component that displays a select with **ALL** the pages

This is extremely big for a dom and also raises an error with lighthouse
<img width="521" alt="Screenshot 2023-02-10 at 15 14 54" src="https://user-images.githubusercontent.com/1783126/218040165-75220da8-0c94-48f8-8b4c-0b07ff930193.png">

Opening this component takes about 4sec just to rerender it.

We need to improve this pagination with the sole goal of **removing this select with all the pages**.
- We could keep the select but only display the next 10 pages
- We could replace with a text field where user could put the page
- We could simply remove that
- We could replace with a classic `1, 2, 3...n-2, n-1, n` or `1, 2, 3, ... n/2-1, n/2, n/2 + 1 ... n-2, n-1, n`
- We could paginate the pages with an infinite scroll
- We could use a virtual scroll

@EmmanuelDrouin I would love your thoughts on that UX wise

**Comment by EmmanuelDrouin** [comment]
@antho1404 regarding the goal of this task and timeline for implementation, I would suggest going with:

Option 1  > "We could replace with a classic 1, 2, 3...n-2, n-1, n or 1, 2, 3, ... n/2-1, n/2, n/2 + 1 ... n-2, n-1, n" which is a classic mechanism for pagination, still allowing users to select a specific page to navigate to (best option for now compared to the current functionalities of the component)
or
Option 2 > "We could simply remove that" and only let the user go to the next or previous page (initial implementation of the component before adding the page selector). This might bring back feedback from users, we initially had, regarding the fact that this doesn't allow navigation to a specific page (one at a time)

**Comment by NicolasMahe** [comment]
There is one option missing:
- We could replace this select component from ChakraUI by the default one. Need to check in this improve the performance tho

**Comment by NicolasMahe** [comment]
For info, the admin has a similar pagination component but use the default's browser selector, and it seems to work just fine with currently 948 pages.
Here is the code:
```tsx
<Select
  cursor="pointer"
  w="96px"
  bg="white"
  id="page"
  onChange={(e) => goTo(parseInt(e.target.value, 10))}
  defaultValue={page}
  alignSelf={{ base: 'start', md: 'end' }}
>
  {Array.from({ length: totalPage }, (_, i) => i + 1).map(
    (page) => (
      <option key={page} value={page}>
        {page.toString()}
      </option>
    ),
  )}
</Select>
```

**Comment by antho1404** [comment]
Related to the feedback [here](https://github.com/liteflow-labs/starter-kit/issues/178#issuecomment-1430754267), I would say let's go with a simple select, if that solves the issue, great, if not, we can implement [option 1](https://github.com/liteflow-labs/starter-kit/issues/178#issuecomment-1427681151) that @EmmanuelDrouin proposes.
