### ISSUE TITLE
Normalize filters in graphql

### ISSUE THREAD

**Issue by antho1404** [liteflow-labs/starter-kit#219]
Filters can either be an object (where all the keys are used as and AND condition) or this array that we need to force the `and`. Having the object is just the way we use it everywhere else, so this would make the codebase consistent. Right now, we had this `and` just because we needed to enforce this `ownershipExists` all the time.

_Originally posted by @antho1404 in https://github.com/liteflow-labs/starter-kit/pull/218#discussion_r1126277182_

**Comment by ismailToyran** [comment]
https://github.com/liteflow-labs/starter-kit/pull/345
Closing in favor of the PR above.
After discussion there, it's better to keep as it's.
