### ISSUE TITLE
New values for locale or remove locale for traits

### ISSUE THREAD

**Issue by ismailToyran** [liteflow-labs/starter-kit#221]
We should either add all traits that are belong to category to the translate folder or use the ones that come from API only.
Using fallback still throws annoying none stop warning to the console

![image](https://user-images.githubusercontent.com/33982052/223360047-b6db1450-6bd9-4f88-a361-006e411e998c.png)

**Comment by antho1404** [comment]
fixed by https://github.com/liteflow-labs/starter-kit/pull/300
