### ISSUE TITLE
Creation of Offer form is not working after refreshing the page

### ISSUE THREAD

**Issue by NicolasMahe** [liteflow-labs/starter-kit#260]
The creation of Offer form is not working after refreshing the page. Clicking the button "Create offer" doesn't do anything, not even input validation.
It's working only when I first navigate to the token page, and the load this page by clicking on the button "sell collectible"

**Comment by antho1404** [comment]
Nice catch, we actually have this issue for a long time, and it is already in production. From the first look, it seems that chakra is not rendering the button as type submit for some reason when rendered by the server
