### ISSUE TITLE
Improve skeleton for pages with filters/sort

### ISSUE THREAD

**Issue by antho1404** [liteflow-labs/starter-kit#302]
Pages with filter/sorts have the skeleton, but because we need the skeleton, the initial loading with https://github.com/liteflow-labs/starter-kit/pull/300 also displays the skeleton even tho data are already available.

The explore pages have the skeleton when loading, filtering, and sorting, while the account pages don't have these skeletons resulting in an initial load with no skeleton.

We need to normalize this and, even better, find a way that could "disable" the skeleton for the first load but not after.
Maybe some things with `initialFetchPolicy`, `nextFetchPolicy`, maybe delaying the `cache-and-network` only after the component is mounted with a `useEffect`

**Comment by NicolasMahe** [comment]
This is fixed by https://github.com/liteflow-labs/starter-kit/pull/328
