### ISSUE TITLE
Replace page selector in pagination component

### ISSUE THREAD

**Issue by NicolasMahe** [liteflow-labs/starter-kit#324]
The page selector is super slow to load on pages that have many pages in the pagination.

For example, on the explore page of Uaan with 37,171 pages, it takes many seconds to open and basically freeze the whole UI with opening: https://dev.uaan.liteflow.com/explore

I remember we already discuss about it but the problem is still present.

**Comment by ismailToyran** [comment]
Closed with https://github.com/liteflow-labs/starter-kit/pull/348
