### ISSUE TITLE
Add skeleton loading to pagination in explore page

### ISSUE THREAD

**Issue by NicolasMahe** [liteflow-labs/starter-kit#340]
With PR https://github.com/liteflow-labs/starter-kit/pull/323, the pagination is executed separately and only client side,  a skeleton should be added while it's loading. This concern the explore page.

https://github.com/liteflow-labs/starter-kit/pull/323#discussion_r1241770442

**Comment by ismailToyran** [comment]
Closed with https://github.com/liteflow-labs/starter-kit/pull/348
