### ISSUE TITLE
Currency selector does not display the name

### ISSUE THREAD

**Issue by antho1404** [liteflow-labs/starter-kit#385]
When selecting a currency in the UI we only display the symbol and not the name in the selector, this is confusing, especially in a multi-chain environment. We had some issues because clients changed the symbol to have the chain in it which is I believe the reason why.
We should display the name of the currency in this select box

<img width="476" alt="Screenshot 2023-08-25 at 10 38 27" src="https://github.com/liteflow-labs/starter-kit/assets/1783126/b895559b-656d-4bc8-8d1e-9bd7bc3fb3ea">

**Comment by ismailToyran** [comment]
https://github.com/liteflow-labs/starter-kit/pull/387 has been added with this PR
