### ISSUE TITLE
Cart system feedbacks

### ISSUE THREAD

**Issue by NicolasMahe** [liteflow-labs/starter-kit#489]
Let's centralize here the cart system feedbacks to not block PR https://github.com/liteflow-labs/starter-kit/pull/471

**Comment by NicolasMahe** [comment]
- [ ] Add a go back button when displaying an error. It's really annoying to close the cart and reopen again
<img width="367" alt="Screenshot 2023-11-29 at 15 48 32" src="https://github.com/liteflow-labs/starter-kit/assets/5823445/13f9a3cf-cbaa-47b1-843b-27f7b4d3f42b">

- [ ] Replace the network icon on the button "Continue with [icon]" by the network name
<img width="367" alt="Screenshot 2023-11-29 at 15 50 21" src="https://github.com/liteflow-labs/starter-kit/assets/5823445/1b7c9577-7257-46b9-8125-f5e7511c39a7">

- [ ] The hover and click area on the nft in the cart doesn't match. I need to click on the picture or texts to be redirected to the nft.
<img width="367" alt="Screenshot 2023-11-29 at 15 53 10" src="https://github.com/liteflow-labs/starter-kit/assets/5823445/6085f6ae-871f-4f65-9521-e19084fc4dd9">

- [ ] Add html hint / tooltip on the add to cart and remove from cart button. As a user I'm not sure what action the icons are going to trigger, specially the `-` button:
<img width="367" alt="Screenshot 2023-11-29 at 15 54 27" src="https://github.com/liteflow-labs/starter-kit/assets/5823445/ecb9d69c-23f2-4a58-8678-adb431be0f7b">

- [ ] Open the cart when I add a NFT. It's not super obvious how to open the cart.

- [ ] No more modal with the transaction status? Specially when doing the approval, it takes time and I don't have much info.

- [ ] There is no selection of quantity for ERC1155. It purchase one edition only. Is that normal? Do we plan to add it later?

**Comment by EmmanuelDrouin** [comment]
Feedback based on Nicolas proposal:
- I agree on all feedback if I do not comment those

> The hover and click area on the nft in the cart doesn't match. I need to click on the picture or texts to be redirected to the nft.

I think we should only give the ability here to get redirected to the item and not the collection. I feel like this will be more efficient for the users. This is the behavrio on Opensea and Rarible, you can only get redirected to the item, no link to the collection

> Open the cart when I add a NFT. It's not super obvious how to open the cart.

This is not something we should do, it will become very annoying for users to have to close the cart every time they add items. You can compare with OpenSea, Rarible, Looksrare and so on, nobody is opening the cart when adding an item.


## My feedback (WIP)

### UI
- The Width of the cart is pretty small, compared to Opensea and Rarible I think we could extend it to give more spaces for the content (currently very very truncated)
- Summary screen > Keep the same consistency in displaying assets in terms of style as the previous screen (rounded corner, not fully rounded, same info with collection/name). As well as same order, between those 2 screens the order changes which downgrade the accessibility for a user
  - First screen
    - <img width="388" alt="Screen Shot 2566-12-08 at 17 59 48" src="https://github.com/liteflow-labs/starter-kit/assets/15095289/c52a9982-9f57-41cd-a5d3-636151996228">
  - Second screen with the wrong style 
    -  <img width="360" alt="Screen Shot 2566-12-08 at 18 00 30" src="https://github.com/liteflow-labs/starter-kit/assets/15095289/c91d26b5-5215-4bbc-abf7-7141c055d99d">

### UX
Purchase with all items on the same chain (only 1 chain in the cart)
- After you successfully purchase your asset, the actionable route is only the explorer.
  - Change style for secondary button 
  - Add primary button below to redirect to the user "owned" page to see the NFTs he just purchased

Purchase with items on different chains (multiple chains in the cart) 
- add button to continue checkout on other chain without "closing/re-opening" the cart

**Comment by EmmanuelDrouin** [comment]
@ismailToyran did you implement my feedback UI/UX as well from this issue? Can we close this issue if all the work left is tracked on dedicated issues?
