### ISSUE TITLE
Remove account in queries

### ISSUE THREAD

**Issue by antho1404** [liteflow-labs/starter-kit#496]
Now that the unlockable content has been removed https://github.com/liteflow-labs/starter-kit/pull/493, we could remove the account from some queries, this account was added to ensure the query is refreshed when the user switches account because the 'hasUnlockatedContent' was account dependent. Now assets should always be the same regardless of the account

**Comment by ismailToyran** [comment]
I've checked each file on https://github.com/liteflow-labs/starter-kit/pull/493
But I couldn't find any file that were dependant on account to refresh.
Could you show me one example, so I fix and close this?

**Comment by antho1404** [comment]
I just had a look and actually most requests are now dependent of the account because we fetch the amount owned so all good to keep
