### ISSUE TITLE
Fix error when login with metamask on mobile

### ISSUE THREAD

**Issue by antho1404** [liteflow-labs/starter-kit#51]
On mobile, to use metamask, users need to open the website from the metamask app.
Currently, we keep the metamask link, but it does nothing if open from a normal browser on mobile.
We should either redirect to the "download metamask" or have some ways to explain to the user that they need to open with the metamask app or simply disable/remove the button.

We can try to detect if metamask is present. If I remember correctly we can check the `window.ethereum` but it needs to be checked.

**Comment by EmmanuelDrouin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Medium priority - Fix error when login with metamask on mobile](https://trello.com/c/xJUiC2YE/527-medium-priority-fix-error-when-login-with-metamask-on-mobile)

**Comment by antho1404** [comment]
closed by https://github.com/liteflow-labs/starter-kit/pull/230
