### ISSUE TITLE
Profile DataTable links

### ISSUE THREAD

**Issue by EmmanuelDrouin** [liteflow-labs/starter-kit#52]
Bids/Trades/Offers tabs on users' profiles are missing links to improve the UX.

## Todo
- [ ] Add links to the table data
  - Item > redirect to the NFT detail page on click
  - User > redirect to the user profile on click

**Comment by EmmanuelDrouin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Medium priority - Profile DataTable links](https://trello.com/c/5weJXlZ1/523-medium-priority-profile-datatable-links)

**Comment by NicolasMahe** [comment]
closed by https://github.com/liteflow-labs/starter-kit/pull/213
