### ISSUE TITLE
Missing empty states for tables

### ISSUE THREAD

**Issue by antho1404** [liteflow-labs/starter-kit#54]
Tables like bids, sales etc.. do not contain any empty state making them simply empty with no call to action as it can be in the admin panel

**Comment by EmmanuelDrouin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Missing empty states for tables](https://trello.com/c/9wz4vKzk/524-missing-empty-states-for-tables)

**Comment by NicolasMahe** [comment]
Closed bt https://github.com/liteflow-labs/starter-kit/pull/216
