### ISSUE TITLE
Move NEXT_PUBLIC_HOME_TOKENS and NEXT_PUBLIC_FEATURED_TOKEN out of Vercel's env

### ISSUE THREAD

**Issue by NicolasMahe** [liteflow-labs/starter-kit#57]
Hodooi bsc mainnet deployment reaches the limit of 4kb on env quite regularly.
The biggest env we have are `NEXT_PUBLIC_HOME_TOKENS` and `NEXT_PUBLIC_FEATURED_TOKEN`.
We should move them out of the Vercel's env in a file in the source code.

**Comment by EmmanuelDrouin** [comment]
@NicolasMahe is this issue still relevant?

**Comment by NicolasMahe** [comment]
We didn't have the problem since a long time and the good fix would be to implement a dedicated admin for hodooi so they can manage this themself. Closing this issue.
