### ISSUE TITLE
Bundle size improvements

### ISSUE THREAD

**Issue by NicolasMahe** [liteflow-labs/starter-kit#58]
Stuff to try to reduce the bundle size:
- https://twitter.com/joebell_/status/1554108255269699584?t=mG4-zknKkO8iWwW28NW1KQ&s=31
- are map files useful? are they removed from final bundle?

Also remove jimp that is currently not used:
https://github.com/liteflow-labs/nft/blob/460090f675cb4f2e764512df2f4c6a7c48d7f3d1/packages/hooks/package.json#L30

**Comment by EmmanuelDrouin** [comment]
@antho1404 how important is this improvement? Seems like something we will not prioritize at the moment, can you confirm and if so I will close this issue
