### ISSUE TITLE
Coinbase Wallet Chrome Extension takes precedence on Metamask

### ISSUE THREAD

**Issue by achampagnedev** [liteflow-labs/starter-kit#59]
When you have the Chrome Extension for Coinbase Wallet installed, if you try to login to MetaMask, it will Open the Coinbase Wallet instead of MetaMask. I noticed that sometimes I will open Both wallets.

**Comment by EmmanuelDrouin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [High priority - Coinbase Wallet Chrome Extension takes precedence on Metamask](https://trello.com/c/RWXRkwdH/526-high-priority-coinbase-wallet-chrome-extension-takes-precedence-on-metamask)

**Comment by NicolasMahe** [comment]
I don't think there is anything we can do about this.
This is related to the way the wallet injected themself in the website.
Users have to deactivate in their browser plugins the wallet they don't want to use.

**Comment by EmmanuelDrouin** [comment]
I would like to investigate this part more before providing an answer on what we can/cannot do here

**Comment by achampagnedev** [comment]
> I don't think there is anything we can do about this. This is related to the way the wallet injected themself in the website. Users have to deactivate in their browser plugins the wallet they don't want to use.

Same for me also with Phantom Wallet, I have to keep it deactivated when I don't use it.

**Comment by antho1404** [comment]
closed by https://github.com/liteflow-labs/starter-kit/pull/230
