### ISSUE TITLE
Coinbase wallet issue when accepting transactions

### ISSUE THREAD

**Issue by achampagnedev** [liteflow-labs/starter-kit#60]
When accepting transactions (on the mobile app but could be on the browser extension as well) it fails when you try to approve. The issue is currently on prod.

**Comment by EmmanuelDrouin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [High priority - Coinbase wallet issue when accepting transactions](https://trello.com/c/dSvL4nZf/525-high-priority-coinbase-wallet-issue-when-accepting-transactions)

**Comment by EmmanuelDrouin** [comment]
Closing this issue as it has been fixed
