### ISSUE TITLE
Marketplace grid improvements.

### ISSUE THREAD

**Issue by achampagnedev** [liteflow-labs/starter-kit#61]
As done in : https://github.com/liteflow-labs/nft/pull/1718

There are some fixes to be done to the grid to make it larget and more responsive.

- [ ] Improvements on token cards images
- [ ] Improvements on grid width for explore page, profile pages
- [ ] Improvements on responsive of grid elements.
- [ ] General improvements for mobile

**Comment by EmmanuelDrouin** [comment]
Closing this issue as this won't be prioritized
