### ISSUE TITLE
Deactivate Apollo client cache

### ISSUE THREAD

**Issue by NicolasMahe** [liteflow-labs/starter-kit#63]
I would like to open the discussion about completely removing the cache of Apollo.

Currently, the codebase doesn't properly implement the cache system of Apollo.

Only type `Account` is setup to merge data with the same `address` and I'm not even sure why.

Apollo seems to cache by default lazy query (bug because of cache on lazy query: https://github.com/liteflow-labs/nft/pull/1948) but not on all version.

My suggestion is to deactivate the cache of Apollo for now:
```diff
return new ApolloClient({
    link: authLink.concat(httpLink),
    cache: new InMemoryCache({
      typePolicies: {
        Account: {
          keyFields: ['address'],
        },
      },
    }),
    ssrMode,
+    defaultOptions: {
+      query: {
+        fetchPolicy: 'no-cache',
+      },
+      mutate: {
+        fetchPolicy: 'no-cache',
+      },
+      watchQuery: {
+        fetchPolicy: 'no-cache',
+      },
    },
  })
```
https://github.com/liteflow-labs/nft/blob/4ebf01b1a77741542576296efdbd7e70a0081f6f/packages/components/src/client.ts#L51-L61

This will help remove any side-effect caused by un-wanting cache.

We can always activate the cache per request if we need to.

@liteflow-labs/nft-marketplace I would like to have your feedback on this one.

**Comment by EmmanuelDrouin** [comment]
@antho1404 could you elaborate on the "effort" required for this? Chris is mentioning a "big refactor" I would like to understand the effort on our side to take a decision on this issue ;)

**Comment by antho1404** [comment]
This still needs more research to see if it even makes sense to remove the cache because of the SSR. For information, I have already started to work on some improvements on the SSR and the apollo client/cache here https://github.com/liteflow-labs/starter-kit/pull/118. This will give more answers

**Comment by antho1404** [comment]
fixed by https://github.com/liteflow-labs/starter-kit/pull/300
