### ISSUE TITLE
TokenCard has some wrong typing on properties

### ISSUE THREAD

**Issue by achampagnedev** [liteflow-labs/starter-kit#64]
On the explore page: 
<img width="1809" alt="image" src="https://user-images.githubusercontent.com/10590599/186328454-e3074cd8-5170-40a9-9371-f316279713c2.png">

On the create page:
<img width="1426" alt="image" src="https://user-images.githubusercontent.com/10590599/186328488-43c98846-0be2-4875-9caf-e4302030aa94.png">

The types in `components/src/Token/Card.tsx`:
<img width="1119" alt="image" src="https://user-images.githubusercontent.com/10590599/186328597-6506dc7c-b7ad-4830-98b5-bf58d7af1d4a.png">

Let's check all the different types received and fix them as needed.

From https://github.com/liteflow-labs/nft/pull/1954#discussion_r953290986

**Comment by EmmanuelDrouin** [comment]
@antho1404 could you tell me how "critical" is this bug? I don't understand the impact of this

**Comment by antho1404** [comment]
Not super critical, basically some code quality, but I'm not even sure that's still valid anymore.
Let's close and reopen when needed

**Comment by NicolasMahe** [comment]
The fix is super simple from what I see, basically adding `| undefined` to all props and replace the default value `""` by `undefined` in the create asset form page.

**Comment by EmmanuelDrouin** [comment]
This won't be prioritize so good on my side to close this issue
