### ISSUE TITLE
Change test app theme to make sure all headings are not the size of base text

### ISSUE THREAD

**Issue by achampagnedev** [liteflow-labs/starter-kit#65]
Base text is 16px but some headings are also using 16px. It can cause some issues that prevents us to see possible issues in text size like in that case where one is a `<Heading variant="h3">` and the other is bast text but they look the same. Compared with ONLYSHOOT who has a different text size for both

<img width="562" alt="image" src="https://user-images.githubusercontent.com/10590599/187830411-874578af-6ccc-4630-bd7e-6fad1e00dfc8.png">

<img width="898" alt="image" src="https://user-images.githubusercontent.com/10590599/187830517-659e7a32-4505-4727-907d-7b8ae62dfda5.png">

**Comment by EmmanuelDrouin** [comment]
Closing this issue as this won't be prioritized
