### ISSUE TITLE
Theming: We need to removed colors using opacity

### ISSUE THREAD

**Issue by achampagnedev** [liteflow-labs/starter-kit#74]
With tailwind we were using the utility class `brand500/10` which creates a color base on `brand500` and makes it 10% opacity.

We need to remove this in the case that the colors are solid and dont need transparency. We need to add the 50 color and make sure that all places using this utility class to create colors. To create add solid `50` color by colorpicking the result of the previous `50` color created with opacity same for others or create new one

reference comments: 
https://github.com/liteflow-labs/nft/pull/2091/files#r982237956
https://github.com/liteflow-labs/nft/pull/2112/files#r985419366

To update: 

- [ ] `@nft/packages` remove `brand500/5 brand500/10`

**Comment by EmmanuelDrouin** [comment]
Closing this issue as this won't be prioritize
