### ISSUE TITLE
Missing server side rendering on queries

### ISSUE THREAD

**Issue by NicolasMahe** [liteflow-labs/starter-kit#75]
Missing SSR on those query:
- [ ] packages/templates/src/users/Form.tsx
- [ ] apps/admin/layouts/layout.tsx
  - This one may be tricky because it's a layout
- [ ] packages/components/src/Navbar/Navbar.tsx
  - This one may be tricky because it's inside a component and not in a page or template.

**Comment by EmmanuelDrouin** [comment]
@NicolasMahe is this issue still relevant with our current new organization for the starter kit?

**Comment by NicolasMahe** [comment]
Yes this is still relevant. The files may have changed, but we should check all the starter-kit properly implement SSR queries

**Comment by antho1404** [comment]
FYI some work I started on the SSR might solve this https://github.com/liteflow-labs/starter-kit/pull/118

**Comment by antho1404** [comment]
closing this one as the recent work on ssr does solve these issues
