### ISSUE TITLE
Redirect to login instead of throwing error if user is not connected on template Notification

### ISSUE THREAD

**Issue by NicolasMahe** [liteflow-labs/starter-kit#76]
We should redirect the user on the login page if user is not connected on `packages/templates/src/notification/Notification.tsx`. Error throwing is line 24

**Comment by EmmanuelDrouin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Redirect to login instead of throwing error if user is not connected on template Notification](https://trello.com/c/5EM3X6gH/520-redirect-to-login-instead-of-throwing-error-if-user-is-not-connected-on-template-notification)

**Comment by antho1404** [comment]
This is already fixed
