### ISSUE TITLE
Improve flickering when account changes, login, or logout

### ISSUE THREAD

**Issue by NicolasMahe** [liteflow-labs/starter-kit#77]
Since https://github.com/liteflow-labs/nft/pull/2075, when the user login or logout on one the following pages, the UI is rendered with an intermediate blank state:

https://user-images.githubusercontent.com/5823445/193965886-f34051b2-e871-4d77-a03b-6c94dee9559f.mov

Here are the pages in template when this issue occurs (always because the query is using a variable with the account's address):
- [ ] `useFetchAssetQuery` in `packages/templates/src/asset/Detail.tsx`
- [ ] `useFetchCategoriesAndAccountQuery` in `packages/templates/src/asset/Form.tsx`
- [ ] `useFetchHomePageQuery` in `packages/templates/src/home/Home.tsx`
- [ ] `useOfferForAssetQuery` in `packages/templates/src/offers/Form.tsx`
- [ ] `useFetchAccountVerificationStatusQuery` in https://github.com/liteflow-labs/nft/pull/2123/files#diff-25c058c98646a585ec1e6d205a486ae96318511366406dba4c828481e4b37293R55 (also missing fallback to account from server)

---

I investigate for a solution and I find out that Apollo set the data of the query to undefined as soon as it starts a new fetch.
This cause the UI to re-render but without data. When Apollo gets the data, a new render is executed with the data.
This is a change in Apollo from v2 to v3 and some people complain: https://github.com/apollographql/apollo-client/issues/6866

Apollo quickly introduced after this breaking change a new variable `previousData` that contains the data from the previous fetch if any to let the developer access previous data.

The simple solution to fix this issue is to add `previousData` as default of `data`.

Here is an example of this solution on `packages/templates/src/asset/Detail.tsx`
```diff
 const {
-  data
+  previousData,
+  data = previousData, // fallback to previousData when the query is loading
   refetch,
 } = useFetchAssetQuery({
   variables: {
     id: assetId,
     now: date,
     address: (ready ? account?.toLowerCase() : currentAccount) || '',
   },
 })
```

Here is the result with this change:

https://user-images.githubusercontent.com/5823445/193966038-c3874e22-ddcd-47b1-ad22-d8a9ed621b04.mov

Even better, we can display the `NProgress` loading animation while the query is loading:
```diff
 const {
-  data
+  previousData,
+  data = previousData, // fallback to previousData when the query is loading
   refetch,
+  loading,
 } = useFetchAssetQuery({
   variables: {
     id: assetId,
     now: date,
     address: (ready ? account?.toLowerCase() : currentAccount) || '',
   },
 })

+ // show NProgress when query is loading
+ useEffect(() => {
+  if (loading) NProgress.start()
+  else NProgress.done()
+ }, [loading])
```

https://user-images.githubusercontent.com/5823445/193966268-898f77f2-a6a7-4407-a4b3-25269808163c.mov

Here is a draft PR that implement this changes in Token Detail page so you can try by yourself: https://github.com/liteflow-labs/nft/pull/2129

@antho1404 @achampagnedev What do you think guys? Would it make sense to add the `previousData` fallback on almost all queries?

**Comment by EmmanuelDrouin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Medium priority - Improve flickering when account changes, login, or logout](https://trello.com/c/e7Iq96lY/519-medium-priority-improve-flickering-when-account-changes-login-or-logout)

**Comment by antho1404** [comment]
fixed by https://github.com/liteflow-labs/starter-kit/pull/300
