### ISSUE TITLE
Add better explanation how the "you will receive" is calculated

### ISSUE THREAD

**Issue by NicolasMahe** [liteflow-labs/starter-kit#79]
When creating a listing, the UI displayed the following:

Price per edition: 0.0005 USDC
Quantity for sale: 3 editions
Total service fee 2.5%: 0.000036 USDC
Total royalties 10%: 0.00015 USDC
Total you will receive: 0.001464 USDC

But actually, I received ~~0.001313~~ 0.001463  USDC

https://mumbai.polygonscan.com//tx/0x5862def29d8d54ca42d933117b3e26655f36c5ab00edd0b57fba155f9331700d

~~Looks like the royalties are not included in the fees.~~

EDIT:

I got very confused because the UI is the same if the royalties are added to the "you will receive" or not, depending if i'm the creator of the NFT:

I'm the creator:
<img width="785" alt="image (1)" src="https://user-images.githubusercontent.com/5823445/196175891-5595f094-fdbf-4ee2-bab4-e1b10b2c40bb.png">

I'm NOT the creator:
<img width="762" alt="image" src="https://user-images.githubusercontent.com/5823445/196175904-1a108268-3c56-4957-9fc1-de330898472f.png">

The UI should be different if the royalties are included in the "you will receive" or not.

**Comment by EmmanuelDrouin** [comment]
Closing this issue as this won't be prioritize
