### ISSUE TITLE
Improve UX of Creation Restricted to Verified Users

### ISSUE THREAD

**Issue by NicolasMahe** [liteflow-labs/starter-kit#80]
The UI of "Creation Restricted to Verified Users" doesn't tell the user to login:

<img width="1252" alt="Screenshot 2022-10-07 at 11 43 05" src="https://user-images.githubusercontent.com/5823445/194469345-d9fa892c-8824-485f-9420-8f37a1a32c3c.png">

My account is actually verified, but I'm not logged in.

**Comment by EmmanuelDrouin** [comment]
Closing this issue as this won't be prioritize
