### ISSUE TITLE
Improve UX of the transaction/signature modal

### ISSUE THREAD

**Issue by NicolasMahe** [liteflow-labs/starter-kit#81]
When creating a nft, a modal is display with 2 steps: upload file and sign transaction.
This is fine until I sign the transaction.
The second step is replaced by a third step "check ownership".
Why this third step is not displayed since the beginning?

I would expect to have all the steps displayed when the modal open, and only their icon and text color to change.

---

Also the modal has the following subtitle all the time, even when i'm waiting for the upload:
"Confirm transaction in your wallet to continue, this action will cost you gas fees.".
This message could be simply removed and the user can follow the steps and their indications.

---

@EmmanuelDrouin what do you think?

**Comment by EmmanuelDrouin** [comment]
Closing this issue as this won't be prioritize
