### ISSUE TITLE
Normalize color in theme

### ISSUE THREAD

**Issue by NicolasMahe** [liteflow-labs/starter-kit#82]
I see there are some color implemented in the theme of app but not in the theme of components.
It can create some differences between what is display in the app and the storybook of components

For example, brand 700, 800, 800 are in app but not in components

Related files:
- https://github.com/liteflow-labs/nft/blob/main/apps/test/styles/theme.ts
- https://github.com/liteflow-labs/nft/blob/main/packages/components/src/baseTheme.ts

I would suggest first:
- make sure any color used in the components AND templates packages are defined in theme of components
- make sure client's app have the right color and overwrite

And then, more a open question:
- Why the test app have a custom colors? What is the point of this?

**Comment by EmmanuelDrouin** [comment]
Closing this issue as this won't be prioritize
