### ISSUE TITLE
Replace all size in px by "name"

### ISSUE THREAD

**Issue by NicolasMahe** [liteflow-labs/starter-kit#83]
Conversation started here: https://github.com/liteflow-labs/nft/pull/2154#discussion_r992357780

Replace all size defined in px by the equivalent Chakra "name" number.

Update size in UI that doesn't exist in Chakra to one that exist to follow the 8px rule
~~If some are missing, need to add them to the theme.~~

**Comment by EmmanuelDrouin** [comment]
Closing this issue as this won't be prioritize
