### ISSUE TITLE
Token Media component improvement

### ISSUE THREAD

**Issue by ismailToyran** [liteflow-labs/starter-kit#85]
Could improve this component according to @cpvdeveloper 's comment:

---

We should avoid mutating props like this. It's recommended to keep props as readonly, because mutating them generally makes things less predictable.

I suggest creating a simple function to return the correct image and animation URLs. Having a single function responsible for this would also be much more testable 

Something like this:
```ts
const getUnlockedContentUrls = (
  unlockedContent: {
    url: string
    mimetype: string | null
  } | null,
  imageUrl: string,
  animationUrl: string | null | undefined,
) => {
  if (unlockedContent) {
    return {
      imageUrl: unlockedContent.url,
      animationUrl: unlockedContent.mimetype?.startsWith('video/')
        ? unlockedContent.url
        : null,
    }
  }
  return {
    imageUrl,
    animationUrl,
  }
}
```
and then in the component....
```tsx
const { imageUrl, animationUrl } = getUnlockedContentUrls(
  unlockedContent,
  image,
  animation,
)
```

**Comment by antho1404** [comment]
@ismailToyran is this still relevant? I think we already did some of the work for this

**Comment by ismailToyran** [comment]
Yes indeed, almost same implementation as well 👍
