### ISSUE TITLE
Report error catch in snackbar to Bugsnag

### ISSUE THREAD

**Issue by NicolasMahe** [liteflow-labs/starter-kit#86]
Error catch and displayed in snackbar are not reported to Bugsnag.
We should report this error to Bugsnag.

The only issue I can see are some errors may not be "bug" but user's issue (like upload of private file that are already public).

**Comment by EmmanuelDrouin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Report error to Bugsnag](https://trello.com/c/Wxhhi888/119-report-error-to-bugsnag)
