### ISSUE TITLE
Improve params of component AccountImage

### ISSUE THREAD

**Issue by NicolasMahe** [liteflow-labs/starter-kit#87]
The `AccountImage` image has an optional param `size` that default to `32`.
The codebase also define width and height of this composant with params `w` and `h`.

If they don't match, the component with a metamask generated icon is not displayed correctly.

Component:
https://github.com/liteflow-labs/nft/blob/27fcf7f1ea039038579faa2e9d2b5a5ec20a5cfe/packages/components/src/Wallet/Image.tsx#L8-L38

- In some places, only size is set, but not `w` and `h`:
https://github.com/liteflow-labs/nft/blob/79e7c9f152b4fa4f8b3d5d6537d0ca20f3d2f190/packages/components/src/Bid/Bid.tsx#L134-L140
https://github.com/liteflow-labs/nft/blob/d1f2d77c418a71edf1d723e43e0c4a46b2cf1e8c/packages/components/src/Navbar/Navbar.tsx#L356-L362

- In some other, only `w` and `h` with a value of 8 (that match the default size of 32px):
https://github.com/liteflow-labs/nft/blob/27fcf7f1ea039038579faa2e9d2b5a5ec20a5cfe/packages/components/src/Token/Owners/ModalActivator.tsx#L23-L27
https://github.com/liteflow-labs/nft/blob/27fcf7f1ea039038579faa2e9d2b5a5ec20a5cfe/packages/components/src/Token/Owners/ModalActivator.tsx#L35-L39
https://github.com/liteflow-labs/nft/blob/27fcf7f1ea039038579faa2e9d2b5a5ec20a5cfe/packages/components/src/Sales/Auction/Incomplete/FailedReservePrice.tsx#L51-L55
https://github.com/liteflow-labs/nft/blob/27fcf7f1ea039038579faa2e9d2b5a5ec20a5cfe/packages/components/src/Sales/Auction/Incomplete/Successfully.tsx#L55-L59
https://github.com/liteflow-labs/nft/blob/79e7c9f152b4fa4f8b3d5d6537d0ca20f3d2f190/packages/components/src/Sales/Direct/ModalItem.tsx#L78-L83

---

I would like to make sure the `size`, `h` and `w` are properly define.

Suggestions/questions to make it better
1. Make `size` params required and remove its default. This will force the developer to properly set the size
2. Is it necessary to put the `w` and `h` if the `size` is set?
  - If yes, could we force the `w` and `h` directly in the composant `AccountImage` based on the `size`? Careful, the `size` is in pixel but the `w` and `h` are in chakra unit (px/8). I would suggest to switch the `size` to chakra unit and multiply it by 8 when need pixel.

**Comment by EmmanuelDrouin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve params of component AccountImage](https://trello.com/c/z6jv0P5k/518-improve-params-of-component-accountimage)

**Comment by NicolasMahe** [comment]
closed by https://github.com/liteflow-labs/starter-kit/pull/215
