### ISSUE TITLE
Use autocomplete component instead of select

### ISSUE THREAD

**Issue by antho1404** [liteflow-labs/starter-kit#88]
You can go on the place an offer form and select a currency (cf multi-currency) > this one uses the menu component from Chakra (similar to the multi-currency component you shared as an example).
<img width="779" alt="Screen Shot 2565-10-20 at 14 09 24" src="https://user-images.githubusercontent.com/15095289/196880447-c7525689-dc67-4573-a319-5acc4da60695.png">

_Originally posted by @EmmanuelDrouin in https://github.com/liteflow-labs/nft/issues/2190#issuecomment-1285054055_

**Comment by NicolasMahe** [comment]
I don't think this issue is still relevant.
@antho1404 can you confirm / close it?

**Comment by antho1404** [comment]
It will become relevant when there is a lot of data to display on selectors like collections or currencies. For now, this is not the case, so I'm ok to close that and reopen when/if needed
