### ISSUE TITLE
Flash of Navigation when switching pages

### ISSUE THREAD

**Issue by achampagnedev** [liteflow-labs/starter-kit#90]
When switching pages while logged in, the navigation state flashes from "logged out" state to "logged in" state 

Steps to reproduce: 
1. Login
2. Change pages
3. Notice state flash

https://user-images.githubusercontent.com/10590599/207502751-fbfb160f-d1bc-4406-b6b4-36d7e67f44db.mov

**Comment by NicolasMahe** [comment]
I think this is a duplicate of https://github.com/liteflow-labs/marketplace-template/issues/77.
Please close this issue if it's the case.

**Comment by NicolasMahe** [comment]
Let's keep it open then 👍

**Comment by EmmanuelDrouin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Flash of Navigation when switching pages](https://trello.com/c/uhOUqaIC/516-flash-of-navigation-when-switching-pages)

**Comment by NicolasMahe** [comment]
closed by https://github.com/liteflow-labs/starter-kit/pull/187
