### ISSUE TITLE
Implement pagination on ownerships

### ISSUE THREAD

**Issue by NicolasMahe** [liteflow-labs/starter-kit#92]
Need to implement a pagination when fetching owners of an asset on at least the page token detail.

The query in database takes around 2s to 3s to execute.

https://github.com/liteflow-labs/starter-kit/blob/aafa50676ea0a989a4db47042203c37e7108ef73/pages/tokens/%5Bid%5D/index.gql#L45-L51

Check for similar query in the codebase.

**Comment by EmmanuelDrouin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement pagination on ownerships](https://trello.com/c/fspjYwQg/515-implement-pagination-on-ownerships)

**Comment by NicolasMahe** [comment]
done in https://github.com/liteflow-labs/starter-kit/pull/148
