### ISSUE TITLE
Multiline asset's description

### ISSUE THREAD

**Issue by NicolasMahe** [liteflow-labs/starter-kit#94]
The asset's description can contains multiline text but the marketplace doesn't display the return to line.
Example: https://blackmarket.defydisrupt.io/tokens/137-0x2459721446814c33c2b4d0699089899b3cc194be-0
On opensea: https://opensea.io/assets/matic/0x2459721446814c33c2b4d0699089899b3cc194be/0

The description in database is multiline, so this is a issue with the rendering of the description in the frontend.

**Comment by EmmanuelDrouin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Multiline asset's description](https://trello.com/c/eXHcziVV/514-multiline-assets-description)

**Comment by NicolasMahe** [comment]
@ismailToyran let's also implement the multiline on the collection's description as well (actually everything loaded from API that's called `description` can be multiline).

**Comment by antho1404** [comment]
This has been done and released in https://github.com/liteflow-labs/starter-kit/releases/tag/v1.2.0
